include: [".well-known"]
# Site settings
title: "xsited" 
header-img: img/xsited_banner_icon_1100x400.jpeg
email: 
copyright_name: xsited
description: "Follow someone else.  Views are my own."
#baseurl: ""
url: ""
twitter_username: xsited
github_username:  
facebook_username:  
email_username:  
author: "xsited"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
